/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;

/**
 *
 * @author admin
 */
public class ChiTietHDJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChiTietHDJPanel
     */
    public ChiTietHDJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel59 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        btnNewHDCT = new javax.swing.JButton();
        btnThemHDCT = new javax.swing.JButton();
        btnCapNhatHDCT = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblHoaDonCT = new javax.swing.JTable();
        jLabel61 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        btnXoaBN3 = new javax.swing.JButton();
        btnXoaBN4 = new javax.swing.JButton();
        btnXoaBN1 = new javax.swing.JButton();
        btnXoaBN2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 875));

        jLabel56.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 153, 153));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("HÓA ĐƠN CHI TIẾT");

        jLabel58.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Bank_Money_35px.png"))); // NOI18N
        jLabel58.setText("Mã dịch vụ");

        jTextField32.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_more_35px.png"))); // NOI18N

        jTextField33.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        btnNewHDCT.setBackground(new java.awt.Color(255, 255, 255));
        btnNewHDCT.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnNewHDCT.setText("MỚI");
        btnNewHDCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNewHDCT.setContentAreaFilled(false);
        btnNewHDCT.setOpaque(true);
        btnNewHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewHDCTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewHDCTMouseExited(evt);
            }
        });

        btnThemHDCT.setBackground(new java.awt.Color(255, 255, 255));
        btnThemHDCT.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnThemHDCT.setText("THÊM");
        btnThemHDCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThemHDCT.setContentAreaFilled(false);
        btnThemHDCT.setOpaque(true);
        btnThemHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemHDCTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemHDCTMouseExited(evt);
            }
        });

        btnCapNhatHDCT.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhatHDCT.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnCapNhatHDCT.setText("CẬP NHẬT");
        btnCapNhatHDCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCapNhatHDCT.setContentAreaFilled(false);
        btnCapNhatHDCT.setOpaque(true);
        btnCapNhatHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapNhatHDCTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhatHDCTMouseExited(evt);
            }
        });

        tblHoaDonCT.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tblHoaDonCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "01", "001", "006", "001", "Sử dụng đầy đủ dịch vụ", "VIP !!!"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn chi tiết", "Mã hóa đơn", "Mã dịch vụ ", "Mã phòng", "Mã bệnh nhân", "Mô tả", "Ghi chú"
            }
        ));
        tblHoaDonCT.setFocusable(false);
        tblHoaDonCT.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblHoaDonCT.setRowHeight(30);
        tblHoaDonCT.setSelectionBackground(new java.awt.Color(245, 165, 165));
        tblHoaDonCT.setShowVerticalLines(false);
        tblHoaDonCT.getTableHeader().setReorderingAllowed(false);
        jScrollPane13.setViewportView(tblHoaDonCT);

        jLabel61.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_orcid_35px.png"))); // NOI18N
        jLabel61.setText("Mã bệnh nhân");

        jTextField35.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel62.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_collaboration_35px.png"))); // NOI18N
        jLabel62.setText("Mô tả");

        jTextField36.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel63.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_money_bill_wave_35px.png"))); // NOI18N
        jLabel63.setText("Mã hóa đơn");

        jTextField37.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel64.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_book_35px.png"))); // NOI18N
        jLabel64.setText("Ghi chú");

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        btnXoaBN3.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_first_1_35px.png"))); // NOI18N
        btnXoaBN3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN3.setContentAreaFilled(false);
        btnXoaBN3.setOpaque(true);
        btnXoaBN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN3MouseExited(evt);
            }
        });

        btnXoaBN4.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_left_35px.png"))); // NOI18N
        btnXoaBN4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN4.setContentAreaFilled(false);
        btnXoaBN4.setOpaque(true);
        btnXoaBN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN4MouseExited(evt);
            }
        });

        btnXoaBN1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_right_35px.png"))); // NOI18N
        btnXoaBN1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN1.setContentAreaFilled(false);
        btnXoaBN1.setOpaque(true);
        btnXoaBN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN1MouseExited(evt);
            }
        });

        btnXoaBN2.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_last_1_35px.png"))); // NOI18N
        btnXoaBN2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN2.setContentAreaFilled(false);
        btnXoaBN2.setOpaque(true);
        btnXoaBN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58)
                            .addComponent(jLabel61)
                            .addComponent(jLabel62)
                            .addComponent(jLabel63)
                            .addComponent(jLabel64))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextField35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextField36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextField37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jSeparator8))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapNhatHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaBN4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel59)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane13))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel56)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61)
                            .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel62)
                            .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNewHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnThemHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCapNhatHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnXoaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnXoaBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnXoaBN4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnXoaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(104, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewHDCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewHDCTMouseEntered
        btnNewHDCT.setBackground(new Color(229, 229, 229));
        btnNewHDCT.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnNewHDCTMouseEntered

    private void btnNewHDCTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewHDCTMouseExited
        btnNewHDCT.setBackground(new Color(255, 255, 255));
        btnNewHDCT.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnNewHDCTMouseExited

    private void btnThemHDCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHDCTMouseEntered
        btnThemHDCT.setBackground(new Color(229, 229, 229));
        btnThemHDCT.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnThemHDCTMouseEntered

    private void btnThemHDCTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHDCTMouseExited
        btnThemHDCT.setBackground(new Color(255, 255, 255));
        btnThemHDCT.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnThemHDCTMouseExited

    private void btnCapNhatHDCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatHDCTMouseEntered
        btnCapNhatHDCT.setBackground(new Color(229, 229, 229));
        btnCapNhatHDCT.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnCapNhatHDCTMouseEntered

    private void btnCapNhatHDCTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatHDCTMouseExited
        btnCapNhatHDCT.setBackground(new Color(255, 255, 255));
        btnCapNhatHDCT.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnCapNhatHDCTMouseExited

    private void btnXoaBN3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN3MouseEntered

    private void btnXoaBN3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN3MouseExited

    private void btnXoaBN4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN4MouseEntered

    private void btnXoaBN4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN4MouseExited

    private void btnXoaBN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN1MouseEntered

    private void btnXoaBN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN1MouseExited

    private void btnXoaBN2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN2MouseEntered

    private void btnXoaBN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN2MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatHDCT;
    private javax.swing.JButton btnNewHDCT;
    private javax.swing.JButton btnThemHDCT;
    private javax.swing.JButton btnXoaBN1;
    private javax.swing.JButton btnXoaBN2;
    private javax.swing.JButton btnXoaBN3;
    private javax.swing.JButton btnXoaBN4;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTable tblHoaDonCT;
    // End of variables declaration//GEN-END:variables

    
}
