/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author admin
 */
public class CTHoatDongJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CTHoatDongJPanel
     */
    public CTHoatDongJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel68 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        btnNewDV = new javax.swing.JButton();
        btnThemDV = new javax.swing.JButton();
        btnCapNhatDV = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jLabel70 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        btnXoaDV = new javax.swing.JButton();
        btnXoaBN3 = new javax.swing.JButton();
        btnXoaBN4 = new javax.swing.JButton();
        btnXoaBN1 = new javax.swing.JButton();
        btnXoaBN2 = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 875));

        jLabel65.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 153, 153));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("HOẠT ĐỘNG CHI TIẾT");

        jLabel66.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_todo_list_35px.png"))); // NOI18N
        jLabel66.setText("Mã hoạt động chi tiết");

        jTextField38.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel67.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_orcid_35px.png"))); // NOI18N
        jLabel67.setText("Mã bệnh nhân");

        jTextField39.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_more_35px.png"))); // NOI18N

        jTextField40.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        btnNewDV.setBackground(new java.awt.Color(255, 255, 255));
        btnNewDV.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnNewDV.setText("MỚI");
        btnNewDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNewDV.setContentAreaFilled(false);
        btnNewDV.setOpaque(true);
        btnNewDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewDVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewDVMouseExited(evt);
            }
        });

        btnThemDV.setBackground(new java.awt.Color(255, 255, 255));
        btnThemDV.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnThemDV.setText("THÊM");
        btnThemDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThemDV.setContentAreaFilled(false);
        btnThemDV.setOpaque(true);
        btnThemDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemDVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemDVMouseExited(evt);
            }
        });

        btnCapNhatDV.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhatDV.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnCapNhatDV.setText("CẬP NHẬT");
        btnCapNhatDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCapNhatDV.setContentAreaFilled(false);
        btnCapNhatDV.setOpaque(true);
        btnCapNhatDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapNhatDVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhatDVMouseExited(evt);
            }
        });

        tblDichVu.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "01", "01", "Thoải mái, nhẹ nhàng"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hoạt động chi tiết", "Mã hoạt đông", "Mã bệnh nhân", "Mô tả"
            }
        ));
        tblDichVu.setFocusable(false);
        tblDichVu.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDichVu.setRowHeight(30);
        tblDichVu.setSelectionBackground(new java.awt.Color(245, 165, 165));
        tblDichVu.setShowVerticalLines(false);
        tblDichVu.getTableHeader().setReorderingAllowed(false);
        jScrollPane14.setViewportView(tblDichVu);

        jLabel70.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_collaboration_35px.png"))); // NOI18N
        jLabel70.setText("Mô tả");

        jLabel72.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_theme_park_35px.png"))); // NOI18N
        jLabel72.setText("Mã hoạt động");

        jTextField44.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane15.setViewportView(jTextArea7);

        btnXoaDV.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaDV.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnXoaDV.setText("XÓA");
        btnXoaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaDV.setContentAreaFilled(false);
        btnXoaDV.setOpaque(true);
        btnXoaDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaDVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaDVMouseExited(evt);
            }
        });

        btnXoaBN3.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_first_1_35px.png"))); // NOI18N
        btnXoaBN3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN3.setContentAreaFilled(false);
        btnXoaBN3.setOpaque(true);
        btnXoaBN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN3MouseExited(evt);
            }
        });

        btnXoaBN4.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_left_35px.png"))); // NOI18N
        btnXoaBN4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN4.setContentAreaFilled(false);
        btnXoaBN4.setOpaque(true);
        btnXoaBN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN4MouseExited(evt);
            }
        });

        btnXoaBN1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_right_35px.png"))); // NOI18N
        btnXoaBN1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN1.setContentAreaFilled(false);
        btnXoaBN1.setOpaque(true);
        btnXoaBN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN1MouseExited(evt);
            }
        });

        btnXoaBN2.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_last_1_35px.png"))); // NOI18N
        btnXoaBN2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN2.setContentAreaFilled(false);
        btnXoaBN2.setOpaque(true);
        btnXoaBN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN2MouseExited(evt);
            }
        });

        btnExcel.setBackground(new java.awt.Color(255, 255, 255));
        btnExcel.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnExcel.setText("Excel");
        btnExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnExcel.setContentAreaFilled(false);
        btnExcel.setOpaque(true);
        btnExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcelMouseExited(evt);
            }
        });
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel67)
                                    .addComponent(jLabel66)
                                    .addComponent(jLabel70)
                                    .addComponent(jLabel72))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField39, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jTextField38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jTextField44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNewDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThemDV, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCapNhatDV, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(btnXoaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXoaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoaBN4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoaBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel68)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel65)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel66)
                            .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel72)
                            .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNewDV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCapNhatDV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaBN4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewDVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewDVMouseEntered
        btnNewDV.setBackground(new Color(229, 229, 229));
        btnNewDV.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnNewDVMouseEntered

    private void btnNewDVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewDVMouseExited
        btnNewDV.setBackground(new Color(255, 255, 255));
        btnNewDV.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnNewDVMouseExited

    private void btnThemDVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemDVMouseEntered
        btnThemDV.setBackground(new Color(229, 229, 229));
        btnThemDV.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnThemDVMouseEntered

    private void btnThemDVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemDVMouseExited

        btnThemDV.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnThemDVMouseExited

    private void btnCapNhatDVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatDVMouseEntered
        btnCapNhatDV.setBackground(new Color(229, 229, 229));
        btnCapNhatDV.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnCapNhatDVMouseEntered

    private void btnCapNhatDVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatDVMouseExited
        btnCapNhatDV.setBackground(new Color(255, 255, 255));
        btnCapNhatDV.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnCapNhatDVMouseExited

    private void btnXoaDVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaDVMouseEntered
        btnXoaDV.setBackground(new Color(229, 229, 229));
        btnXoaDV.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnXoaDVMouseEntered

    private void btnXoaDVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaDVMouseExited
        btnXoaDV.setBackground(new Color(255, 255, 255));
        btnXoaDV.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnXoaDVMouseExited

    private void btnXoaBN3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN3MouseEntered

    private void btnXoaBN3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN3MouseExited

    private void btnXoaBN4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN4MouseEntered

    private void btnXoaBN4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN4MouseExited

    private void btnXoaBN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN1MouseEntered

    private void btnXoaBN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN1MouseExited

    private void btnXoaBN2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN2MouseEntered

    private void btnXoaBN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN2MouseExited

    private void btnExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcelMouseEntered

    private void btnExcelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcelMouseExited

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatDV;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnNewDV;
    private javax.swing.JButton btnThemDV;
    private javax.swing.JButton btnXoaBN1;
    private javax.swing.JButton btnXoaBN2;
    private javax.swing.JButton btnXoaBN3;
    private javax.swing.JButton btnXoaBN4;
    private javax.swing.JButton btnXoaDV;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTable tblDichVu;
    // End of variables declaration//GEN-END:variables
//       XSSFWorkbook workbook;
//    private CellStyle headerCellStyle() {
//        CellStyle cellStyle = workbook.createCellStyle();
//        cellStyle.setAlignment(org.apache.poi.ss.usermodel.HorizontalAlignment.CENTER);
//        cellStyle.setVerticalAlignment(org.apache.poi.ss.usermodel.VerticalAlignment.CENTER);
//        cellStyle.setBorderBottom(BorderStyle.THICK);
//        cellStyle.setBorderLeft(BorderStyle.THICK);
//        cellStyle.setBorderRight(BorderStyle.THICK);
//        cellStyle.setBorderTop(BorderStyle.THICK);
//
//        org.apache.poi.ss.usermodel.Font font = workbook.createFont();
//        font.setBold(true);
//        font.setFontName("Times New Roman");
//        font.setFontHeight((short) 350);
//        cellStyle.setFont(font);
//        return cellStyle;
//    }
//
//    private CellStyle coCellStyle() {
//        CellStyle cellStyle = workbook.createCellStyle();
//        cellStyle.setAlignment(org.apache.poi.ss.usermodel.HorizontalAlignment.CENTER);
//        cellStyle.setVerticalAlignment(org.apache.poi.ss.usermodel.VerticalAlignment.CENTER);
//        cellStyle.setBorderBottom(BorderStyle.THIN);
//        cellStyle.setBorderLeft(BorderStyle.THICK);
//        cellStyle.setBorderRight(BorderStyle.THICK);
//        cellStyle.setBorderTop(BorderStyle.THIN);
//        org.apache.poi.ss.usermodel.Font font = workbook.createFont();
//        font.setFontName("Times New Roman");
//        font.setFontHeight((short) 250);
//        cellStyle.setFont(font);
//        return cellStyle;
//    }
//    void excel(){
//         JFileChooser chooser = new JFileChooser();
//        chooser.setDialogTitle("Save as");
//        FileNameExtensionFilter f = new FileNameExtensionFilter("xls", "xlsx");
//        FileOutputStream out = null;
//        chooser.setFileFilter(f);
//        int excel = chooser.showSaveDialog(null);
//        if (excel == JFileChooser.APPROVE_OPTION) {
//            try {
//                workbook = new XSSFWorkbook();
//                XSSFSheet spreadsheet1 = workbook.createSheet("Danh sách chuyên đề");
//                XSSFRow rows1 = null;
//                Cell cells1 = null;
//                CellStyle cs = headerCellStyle();
//                CellStyle csc = coCellStyle();
//                rows1 = spreadsheet1.createRow((short) 1);
//                rows1.setHeight((short) 500);
//                cells1 = rows1.createCell(0, CellType.STRING);
//                cells1.setCellValue("Thông tin khoa học");
//                rows1 = spreadsheet1.createRow((short) 2);
//                rows1.setHeight((short) 500);
//                cells1 = rows1.createCell(0, CellType.STRING);
//                cells1.setCellValue("Mã khóa học");
//                cells1.setCellStyle(cs);
//                cells1 = rows1.createCell(1, CellType.STRING);
//                cells1.setCellValue("Chuyên đề");
//                cells1.setCellStyle(cs);
//                cells1 = rows1.createCell(2, CellType.STRING);
//                cells1.setCellValue("Thời lượng");
//                cells1.setCellStyle(cs);
//                cells1 = rows1.createCell(3, CellType.STRING);
//                cells1.setCellValue("Học phí");
//                cells1.setCellStyle(cs);
//                cells1 = rows1.createCell(4, CellType.STRING);
//                cells1.setCellValue("Ngày khai giảng");
//                cells1.setCellStyle(cs);
//                cells1 = rows1.createCell(5, CellType.STRING);
//                cells1.setCellValue("Nhân viên nhập thông tin");
//                cells1.setCellStyle(cs);
//                cells1 = rows1.createCell(6, CellType.STRING);
//                cells1.setCellValue("Ngày tạo");
//                cells1.setCellStyle(cs);
//                List<> list = dao.select();
//                for (int i = 0; i < list.size(); i++) {
//                    KhoaHoc dt = list.get(i);
//                    rows1 = spreadsheet1.createRow((short) 3 + i);
//                    rows1.setHeight((short) 500);
//                    cells1 = rows1.createCell(0);
//                    cells1.setCellValue(dt.getMaKH());
//                    cells1.setCellStyle(csc);
//                    cells1 = rows1.createCell(1);
//                    cells1.setCellValue(dt.getMaCD());
//                    cells1.setCellStyle(csc);
//                    cells1 = rows1.createCell(2);
//                    cells1.setCellValue(dt.getThoiLuong());
//                    cells1.setCellStyle(csc);
//                    cells1.setCellStyle(csc);
//                    cells1 = rows1.createCell(3);
//                    cells1.setCellValue(dt.getHocPhi());
//                    cells1.setCellStyle(csc);
//                    cells1 = rows1.createCell(4);
//                    cells1.setCellValue(DateHelper.toString(dt.getNgayKG()));
//                    cells1.setCellStyle(csc);
//                    cells1 = rows1.createCell(5);
//                    cells1.setCellValue(dt.getMaNV());
//                    cells1.setCellStyle(csc);
//                    cells1 = rows1.createCell(6);
//                    cells1.setCellValue(DateHelper.toString(dt.getNgayTao()));
//                    cells1.setCellStyle(csc);
//                }
//                for (int i = 0; i < 7; i++) {
//                    spreadsheet1.autoSizeColumn(i);
//                }
//                out = new FileOutputStream(chooser.getSelectedFile() + ".xlsx");
//                workbook.write(out);
//                out.close();
//                JOptionPane.showMessageDialog(this, "Xuất file thành công");
//            } catch (Exception e) {
//                System.out.println(e);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Vui lòng chọn ổ đĩa");
//        }
//    }
    
}
