/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Helper.ShareHelper;
import java.awt.Color;

/**
 *
 * @author admin
 */
public class DichVuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DichVuJPanel
     */
    public DichVuJPanel() {
        initComponents();
        if (ShareHelper.isLogin1()) {
            btnThem.setVisible(false);
            btnCapNhat.setVisible(false);
            btnXoa.setVisible(false);
            btnNew.setVisible(false);
        } else {
            btnThem.setVisible(true);
            btnCapNhat.setVisible(true);
            btnXoa.setVisible(true);
            btnNew.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel65 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel68 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        btnXoa = new javax.swing.JButton();
        btnXoaBN3 = new javax.swing.JButton();
        btnXoaBN4 = new javax.swing.JButton();
        btnXoaBN1 = new javax.swing.JButton();
        btnXoaBN2 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 875));

        jLabel65.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 153, 153));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("QUẢN LÝ DỊCH VỤ");

        jLabel67.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_paid_bill_35px.png"))); // NOI18N
        jLabel67.setText("Tên dịch vụ");

        jTextField39.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_more_35px.png"))); // NOI18N

        jTextField40.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel69.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_money_bill_wave_35px.png"))); // NOI18N
        jLabel69.setText("Giá dịch vụ");

        btnNew.setBackground(new java.awt.Color(255, 255, 255));
        btnNew.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnNew.setText("MỚI");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNew.setContentAreaFilled(false);
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThem.setContentAreaFilled(false);
        btnThem.setOpaque(true);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCapNhat.setContentAreaFilled(false);
        btnCapNhat.setOpaque(true);
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseExited(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_collaboration_35px.png"))); // NOI18N
        jLabel70.setText("Mô tả");

        jTextField41.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane15.setViewportView(jTextArea7);

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa.setContentAreaFilled(false);
        btnXoa.setOpaque(true);
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });

        btnXoaBN3.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_first_1_35px.png"))); // NOI18N
        btnXoaBN3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN3.setContentAreaFilled(false);
        btnXoaBN3.setOpaque(true);
        btnXoaBN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN3MouseExited(evt);
            }
        });
        btnXoaBN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBN3ActionPerformed(evt);
            }
        });

        btnXoaBN4.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_left_35px.png"))); // NOI18N
        btnXoaBN4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN4.setContentAreaFilled(false);
        btnXoaBN4.setOpaque(true);
        btnXoaBN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN4MouseExited(evt);
            }
        });

        btnXoaBN1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_right_35px.png"))); // NOI18N
        btnXoaBN1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN1.setContentAreaFilled(false);
        btnXoaBN1.setOpaque(true);
        btnXoaBN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN1MouseExited(evt);
            }
        });

        btnXoaBN2.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBN2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnXoaBN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_last_1_35px.png"))); // NOI18N
        btnXoaBN2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaBN2.setContentAreaFilled(false);
        btnXoaBN2.setOpaque(true);
        btnXoaBN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaBN2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaBN2MouseExited(evt);
            }
        });

        tblHoaDon.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Karoke", "500000", "Thoải mái"},
                {"Phòng tổng thống", "700000", "Ngon"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Giá dịch vụ", "Mô tả"
            }
        ));
        tblHoaDon.setFocusable(false);
        tblHoaDon.setGridColor(new java.awt.Color(255, 255, 255));
        tblHoaDon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblHoaDon.setRowHeight(30);
        tblHoaDon.setSelectionBackground(new java.awt.Color(245, 165, 165));
        tblHoaDon.setShowVerticalLines(false);
        tblHoaDon.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(tblHoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel68)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel67)
                                    .addComponent(jLabel69)
                                    .addComponent(jLabel70))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField39)
                                    .addComponent(jTextField41)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)))
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 633, Short.MAX_VALUE)
                                        .addComponent(btnXoaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoaBN4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoaBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane12))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel65)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel69)
                            .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(241, 241, 241)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaBN4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        btnNew.setBackground(new Color(229, 229, 229));
        btnNew.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        btnNew.setBackground(new Color(255, 255, 255));
        btnNew.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnNewMouseExited

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        btnThem.setBackground(new Color(229, 229, 229));
        btnThem.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited

        btnThem.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnThemMouseExited

    private void btnCapNhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseEntered
        btnCapNhat.setBackground(new Color(229, 229, 229));
        btnCapNhat.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnCapNhatMouseEntered

    private void btnCapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseExited
        btnCapNhat.setBackground(new Color(255, 255, 255));
        btnCapNhat.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnCapNhatMouseExited

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        btnXoa.setBackground(new Color(229, 229, 229));
        btnXoa.setForeground(new Color(0, 204, 106));
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        btnXoa.setBackground(new Color(255, 255, 255));
        btnXoa.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnXoaBN3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN3MouseEntered

    private void btnXoaBN3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN3MouseExited

    private void btnXoaBN4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN4MouseEntered

    private void btnXoaBN4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN4MouseExited

    private void btnXoaBN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN1MouseEntered

    private void btnXoaBN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN1MouseExited

    private void btnXoaBN2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN2MouseEntered

    private void btnXoaBN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaBN2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN2MouseExited

    private void btnXoaBN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaBN3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaBN1;
    private javax.swing.JButton btnXoaBN2;
    private javax.swing.JButton btnXoaBN3;
    private javax.swing.JButton btnXoaBN4;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTable tblHoaDon;
    // End of variables declaration//GEN-END:variables

}
