/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DuAnDAO.NhanVienDAO;
import Entity.NhanVien;
import Helper.RandomStringExmple;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Lenovo
 */
public class QuenMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        lblTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDoiMkSDT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtXacNhanMK = new javax.swing.JPasswordField();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGui = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu mới");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        txtCode.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, 30));

        txtMatKhauMoi.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, 30));

        lblTime.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(130, 145, 239));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("120");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, 40));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setText("Mã code");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        btnDoiMkSDT.setBackground(new java.awt.Color(130, 145, 239));
        btnDoiMkSDT.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        btnDoiMkSDT.setForeground(new java.awt.Color(130, 145, 239));
        btnDoiMkSDT.setText("Đổi mật khẩu bằng SDT");
        btnDoiMkSDT.setBorder(null);
        btnDoiMkSDT.setContentAreaFilled(false);
        btnDoiMkSDT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoiMkSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDoiMkSDT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDoiMkSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMkSDTActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoiMkSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 160, 40));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setText("Mã nhân viên");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtMaNV.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setText("Xác nhận MK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        txtXacNhanMK.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtXacNhanMK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtXacNhanMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 240, 30));

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_24px_1.png"))); // NOI18N
        btnThoat.setContentAreaFilled(false);
        btnThoat.setOpaque(true);
        btnThoat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_24px.png"))); // NOI18N
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThoatMouseExited(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/forgot.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 370, 450));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 174, 143));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đổi mật khẩu bằng email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, 20));

        btnGui.setBackground(new java.awt.Color(130, 145, 239));
        btnGui.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnGui.setForeground(new java.awt.Color(255, 255, 255));
        btnGui.setText("Gửi mã");
        btnGui.setContentAreaFilled(false);
        btnGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGui.setOpaque(true);
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });
        jPanel1.add(btnGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, 40));

        btnXacNhan.setBackground(new java.awt.Color(130, 145, 239));
        btnXacNhan.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setContentAreaFilled(false);
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.setOpaque(true);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 360, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 153));
        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Xin chào ! Chúng tôi là Euphoria");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 390, -1));

        lblHome.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home_25px.png"))); // NOI18N
        lblHome.setText("Về trang chủ");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMkSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMkSDTActionPerformed
        this.SDT();
    }//GEN-LAST:event_btnDoiMkSDTActionPerformed

    private void btnThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseEntered

    }//GEN-LAST:event_btnThoatMouseEntered

    private void btnThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatMouseExited

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        this.sendCode();
    }//GEN-LAST:event_btnGuiActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        this.changePass();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        cancel();
    }//GEN-LAST:event_lblHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhau dialog = new QuenMatKhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMkSDT;
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhanMK;
    // End of variables declaration//GEN-END:variables

    Timer timer;
    boolean testTime = false;
    String code;
    NhanVienDAO dao = new NhanVienDAO();

    public void init() {
        updateStatus();
    }

    public void runClock() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(lblTime.getText());
                if (x > 0) {
                    lblTime.setText(String.valueOf(--x));
                    testTime = true;
                } else {
                    lblTime.setText("120");
                    testTime = false;
                    timer.stop();
                }
                updateStatus();
            }
        });
        timer.start();
    }

    public boolean checkExistID() {
        String maNV = txtMaNV.getText();
        if (!maNV.isEmpty()) {
            if (dao.selectByID(maNV) == null) {
                Helper.DialogHelper.alert(this, "Không tìm thấy mã nhân viên");
                return false;
            } else {
                return true;
            }
        } else {
            Helper.DialogHelper.alert(this, "Bạn chưa nhập mã nhân viên");
            return false;
        }
    }

    public String getEmailByID() {
        String maNV = txtMaNV.getText();
        return dao.selectEmailByID(maNV).getEmail();
    }

    public void sendCodeToEmail() {
        code = new RandomStringExmple().randomAlphaNumeric(8);
        String to = getEmailByID();
        String emailGui = "phiphung123bt@gmail.com";
        String passGui = "khuyethung250902";
        String subject = "Đây là mã code để đổi mật khẩu" + "\nVui lòng nhập trong vòng 120 giây";
        try {
            Properties p = new Properties();
            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");
            p.put("mail.smtp.port", 587);

            Session s = Session.getInstance(p,
                    new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(emailGui, passGui);
                        }
                    });

            Message msg = new MimeMessage(s);
            msg.setFrom(new InternetAddress(emailGui));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setSubject(subject);
            msg.setText(code);

            Transport.send(msg);

            JOptionPane.showMessageDialog(this, "Kiểm tra mã code tại email");
        } catch (Exception e) {
        }
    }

    public void sendCode() {
        if (checkExistID()) {
            runClock();
            sendCodeToEmail();
        }
    }

    public void changePass() {
        if (txtCode.getText().equals(code)) {
            if (validatePassword()) {
                updatePassInDB();
                lblTime.setText("0");
                Helper.DialogHelper.alert(this, "Thay đổi mật khẩu thành công");
            }
        } else {
            Helper.DialogHelper.alert(this, "Mã code không chính xác");
        }
    }

    public boolean validatePassword() {
        String matKhauMoi = new String(txtMatKhauMoi.getPassword());
        String xacNhanMK = new String(txtXacNhanMK.getPassword());
        if (matKhauMoi.isEmpty()) {
            Helper.DialogHelper.alert(this, "Bạn chưa nhập mật khẩu mới");
            txtMatKhauMoi.requestFocus();
            return false;
        } else if (xacNhanMK.isEmpty()) {
            Helper.DialogHelper.alert(this, "Bạn chưa nhập xác nhận mật khẩu");
            txtXacNhanMK.requestFocus();
            return false;
        } else if (!matKhauMoi.equals(xacNhanMK)) {
            Helper.DialogHelper.alert(this, "Xác nhận mật khẩu không chính xác");
            return false;
        }
        return true;
    }

    public void updatePassInDB() {
        NhanVien nv = dao.selectByID(txtMaNV.getText());
        String matKhauMoi = new String(txtMatKhauMoi.getPassword());
        nv.setMatKhau(matKhauMoi);
        dao.update(nv);
    }

    public void updateStatus() {
        txtCode.setEnabled(testTime);
        txtMatKhauMoi.setEnabled(testTime);
        txtXacNhanMK.setEnabled(testTime);
        btnXacNhan.setEnabled(testTime);
        btnGui.setEnabled(!testTime);
        txtMaNV.setEnabled(!testTime);
        if (!testTime) {
            btnGui.setBackground(new Color(130, 145, 239));
            btnXacNhan.setBackground(new Color(128, 128, 128));
        } else {
            btnXacNhan.setBackground(new Color(130, 145, 239));
            btnGui.setBackground(new Color(128, 128, 128));
        }
    }

    public void cancel() {
        this.dispose();
        new Home().setVisible(true);
    }

    public void SDT() {
        this.dispose();
        new QuenMKSDT(null, true).setVisible(true);
    }

}
